const EXPERIENCIAS = [
    // --- EXPERIENCIAS ORIGINALES ---
    {
        id: "EXP001",
        titulo: "El silencio de los bambúes",
        subtitulo: "Cómo encontré la paz en medio del caos de Arashiyama",
        autor: "Laura G.",
        fecha_publicacion: "12/03/2024",
        pack_asociado: "ASIA001JP", 
        imagen1: "../images/japon_bambu.webp",
        imagen2: "../images/japon_bambu.webp",
        parrafo1: "Siempre pensé que Japón sería ruido, neones y gente corriendo por todas partes. Y lo es, especialmente en Tokyo. Pero cuando llegué a Kyoto, algo cambió dentro de mí. El ritmo de la ciudad antigua es diferente, como si el tiempo hubiera decidido tomarse un descanso entre templo y templo.",
        parrafo2: "El momento más mágico fue al amanecer en el bosque de bambú de Arashiyama. Nos levantamos a las 5:00 AM para evitar las multitudes. El frío de la mañana se colaba por la ropa, pero valió la pena. Estar allí sola, escuchando solo el crujir de los troncos chocando con el viento, fue una experiencia casi religiosa.",
        parrafo3: "Después del paseo, nos refugiamos en una pequeña casa de té cercana. Allí probé por primera vez el matcha auténtico, batido con mimo por una anciana que no hablaba ni una palabra de inglés, pero cuya sonrisa entendía perfectamente mi gratitud. Fue un contraste brutal con la noche anterior de karaoke y luces en Osaka.",
        parrafo4: "Recomiendo este viaje a cualquiera que sienta que su vida va demasiado rápido. Japón te enseña que la modernidad más absoluta puede convivir con la tradición más pausada. Volveré, sin duda, para ver los cerezos en flor.",
        likes: 34
    },
    {
        id: "EXP002",
        titulo: "Despertar entre leones",
        subtitulo: "Mi primera vez en un safari y por qué lloré al ver un elefante",
        autor: "Carlos M.",
        fecha_publicacion: "05/02/2024",
        pack_asociado: "AFR004KE", 
        imagen1: "../images/elefante.jpg",
        imagen2: "../images/elefante.jpg",
        parrafo1: "Nada te prepara para la inmensidad de África. Había visto documentales toda mi vida, pero el olor de la tierra mojada y el sonido de la sabana no se pueden transmitir por televisión. Al llegar al Masai Mara, sentí que estaba entrando en el verdadero reino animal, donde nosotros somos solo invitados.",
        parrafo2: "La primera mañana salimos antes de que saliera el sol. Nuestro guía, Joseph, detuvo el jeep de repente y señaló un arbusto. Al principio no vi nada, pero luego, una melena dorada se movió. Un león macho estaba a escasos cinco metros de nosotros, bostezando indiferente a nuestra presencia.",
        parrafo3: "Pero lo que realmente me rompió fue el encuentro con una familia de elefantes. Ver cómo las madres protegían a la cría más pequeña, con esa ternura y fuerza a la vez, me hizo llorar de emoción. Es una lección de humildad brutal darte cuenta de lo pequeños que somos al lado de estos gigantes.",
        parrafo4: "Las noches en el campamento eran otro mundo. Cenar bajo un cielo con más estrellas de las que creía que existían, escuchando hienas a lo lejos, es algo que te cambia la perspectiva. Si tienes dudas sobre si ir a África: ve. Es el viaje de tu vida.",
        likes: 58
    },
    {
        id: "EXP003",
        titulo: "Caminando hacia las nubes",
        subtitulo: "El reto físico y mental de llegar a Machu Picchu",
        autor: "Ana y David",
        fecha_publicacion: "20/01/2024",
        pack_asociado: "LATAM006PE", 
        imagen1: "../images/nubes_MP.jpg",
        imagen2: "../images/nubes_MP.jpg",
        parrafo1: "Llegar a Cusco ya es una aventura en sí misma. La altura se nota nada más bajar del avión, pero la energía de la ciudad te empuja a seguir. Pasamos dos días aclimatándonos, bebiendo mate de coca y perdiéndonos por las calles de piedra que cuentan historias de dos imperios.",
        parrafo2: "El camino hacia Aguas Calientes fue espectacular, viendo cómo el paisaje cambiaba de montañas áridas a selva húmeda. Pero nada se compara al momento en que entras en la ciudadela. Eran las 6 de la mañana y la niebla cubría todo. Poco a poco, el sol empezó a disipar las nubes y Huayna Picchu apareció frente a nosotros.",
        parrafo3: "No es solo ver las ruinas, es entender cómo vivían allí, cómo construyeron algo tan perfecto en un lugar tan inaccesible. Nuestro guía nos explicó la conexión astronómica de cada piedra, y te das cuenta de que los Incas no solo eran constructores, eran ingenieros del universo.",
        parrafo4: "Terminamos el viaje en Lima, disfrutando de la que dicen es la mejor gastronomía del mundo (y confirmamos que el ceviche allí es de otro planeta). Perú es intenso, agotador a veces, pero infinitamente gratificante.",
        likes: 47
    },

    // --- NUEVAS EXPERIENCIAS AÑADIDAS ---

    {
        id: "EXP004",
        titulo: "Experiencia Colombia",
        subtitulo: "Café, salsa y la calidez de su gente",
        autor: "Marta R.",
        fecha_publicacion: "15/04/2024",
        pack_asociado: "LATAM001CO",
        imagen1: "../images/ex-colombia.jpg",
        imagen2: "../images/ex-colombia.jpg", // Placeholder si no tienes variaciones
        parrafo1: "Colombia te atrapa desde el primer 'Buenos días'. Recorrer los paisajes tropicales del Eje Cafetero fue como entrar en una postal verde infinita. El aroma a café recién tostado por las mañanas se convirtió en mi despertador favorito.",
        parrafo2: "En Medellín descubrí una ciudad que ha sabido reinventarse a través del arte y la cultura. Caminar por la Comuna 13 y ver los grafitis llenos de historia fue una lección de resiliencia que me llevo para siempre.",
        parrafo3: "Pero lo mejor, sin duda, es la alegría única del pueblo colombiano. Da igual dónde vayas, siempre hay música, una sonrisa y alguien dispuesto a ayudarte. Bailar salsa (o intentarlo) en Cali fue el broche de oro.",
        parrafo4: "Es un país que rompe con todos los estereotipos. Me sentí segura, bienvenida y parte de una gran familia. Si buscas un destino con alma, Colombia es el lugar.",
        likes: 39
    },
    {
        id: "EXP005",
        titulo: "Vietnam y sus sendas escondidas",
        subtitulo: "Entre arrozales y dragones de piedra",
        autor: "Javier S.",
        fecha_publicacion: "22/05/2024",
        pack_asociado: "ASIA006VN",
        imagen1: "../images/ex-vietnam.jpg",
        imagen2: "../images/ex-vietnam.jpg",
        parrafo1: "Vietnam es un país que se vive con los cinco sentidos. El caos de las motos en Hanoi contrasta con la paz absoluta de navegar por la Bahía de Ha Long, donde las formaciones de roca parecen dragones durmiendo en el mar.",
        parrafo2: "Nos adentramos en templos ancestrales ocultos en cuevas, donde el olor a incienso crea una atmósfera mística. Visitar aldeas flotantes y ver cómo la vida transcurre sobre el agua fue una experiencia antropológica fascinante.",
        parrafo3: "Caminar por senderos rodeados de naturaleza salvaje en Sapa, entre terrazas de arroz de un verde imposible, me hizo conectar con la tierra de una forma nueva. Las etnias locales, con sus trajes coloridos, nos recibieron con curiosidad y amabilidad.",
        parrafo4: "Y la comida... ¡qué decir de la comida! Un simple Pho en un puesto callejero sabe a gloria. Vietnam es un viaje de descubrimiento constante, humilde y espectacular a la vez.",
        likes: 22
    },
    {
        id: "EXP006",
        titulo: "La ruta de los manglares por Panamá",
        subtitulo: "Naturaleza virgen entre dos océanos",
        autor: "Elena y Pablo",
        fecha_publicacion: "10/06/2024",
        pack_asociado: "LATAM007PA",
        imagen1: "../images/ex-panama.jpg",
        imagen2: "../images/ex-panama.jpg",
        parrafo1: "Panamá es mucho más que su famoso canal. Navegar entre manglares fue como entrar en un laberinto de vida. El silencio solo se rompía por el canto de aves exóticas y el chapoteo de los remos.",
        parrafo2: "Descubrimos fauna que nunca habíamos visto en libertad: perezosos colgados de las ramas, monos aulladores y estrellas de mar gigantes en el fondo cristalino. Es uno de los ecosistemas más fascinantes y frágiles que he visitado.",
        parrafo3: "La visita a las islas de Guna Yala nos permitió desconectar del mundo digital y reconectar con lo básico: sol, mar y arena blanca. Dormir en cabañas sencillas frente al Caribe es el verdadero lujo.",
        parrafo4: "Panamá nos sorprendió por su biodiversidad y por lo fácil que es pasar de la selva más densa a una ciudad de rascacielos en pocas horas. Un destino completo y sorprendente.",
        likes: 27
    },
    {
        id: "EXP007",
        titulo: "Exploración de glaciares en Islandia",
        subtitulo: "Caminando sobre el hielo azul eterno",
        autor: "Roberto K.",
        fecha_publicacion: "05/01/2024",
        pack_asociado: "EUR002IS",
        imagen1: "../images/ex-islandia.avif",
        imagen2: "../images/ex-islandia.avif",
        parrafo1: "Islandia parece otro planeta. Ponerse los crampones y caminar sobre antiguas masas de hielo fue una de las cosas más emocionantes que he hecho. El crujido del glaciar bajo tus pies te recuerda que es una entidad viva.",
        parrafo2: "Descubrir cuevas de hielo fue mágico. Los tonos azules son imposibles de describir, parece que estás dentro de un zafiro gigante. La luz se filtra a través del hielo creando efectos visuales que ninguna cámara puede captar del todo.",
        parrafo3: "Más allá del hielo, las cascadas y los campos de lava te dejan sin aliento. Es una tierra de contrastes brutales, donde el fuego y el hielo han moldeado un paisaje dramático y hermoso.",
        parrafo4: "Aunque el frío aprieta, la calidez de los baños termales al final del día lo cura todo. Ver auroras boreales bailando sobre el glaciar fue el regalo final de este viaje épico.",
        likes:60
    },
    {
        id: "EXP008",
        titulo: "Ruta a la Montaña de 7 colores en Perú",
        subtitulo: "Un arcoíris pintado en la tierra",
        autor: "Sofía L.",
        fecha_publicacion: "18/08/2024",
        pack_asociado: "LATAM006PE",
        imagen1: "../images/ex-peru.jpg",
        imagen2: "../images/ex-peru.jpg",
        parrafo1: "El trekking a Vinicunca no es fácil debido a la altitud, pero cada paso merece la pena. El paisaje andino te envuelve, con llamas y alpacas pastando libremente mientras subes hacia la cima.",
        parrafo2: "Cuando por fin llegas al mirador y ves la montaña frente a ti, te quedas sin palabras. Es un trekking único entre paisajes surrealistas, donde los minerales han pintado franjas de turquesa, lavanda y dorado en la ladera.",
        parrafo3: "El viento soplaba fuerte, pero la emoción nos mantenía calientes. Es increíble pensar en los procesos geológicos necesarios para crear algo así. Nos sentimos muy pequeños ante tanta majestuosidad.",
        parrafo4: "Recomiendo ir bien aclimatado y tomarse el ascenso con calma. Llegar arriba es una victoria personal y la vista es la mejor medalla que te puedes llevar.",
        likes: 18
    },
    {
        id: "EXP009",
        titulo: "Cappadocia en globo en Turquía",
        subtitulo: "Amanecer sobre un cuento de hadas",
        autor: "Daniel y Clara",
        fecha_publicacion: "30/09/2024",
        pack_asociado: "", // No tenemos pack de Turquía aún, dejamos vacío o creamos uno futuro
        imagen1: "../images/ex-turquia.jpeg",
        imagen2: "../images/ex-turquia.jpeg",
        parrafo1: "Levantarse a las 4 de la mañana nunca había tenido tanto sentido. Ver cómo inflan los enormes globos en la oscuridad es el preludio de algo inolvidable. Cuando la cesta se despega del suelo, todo es silencio.",
        parrafo2: "Flotar sobre las 'chimeneas de hadas' mientras el sol empieza a iluminar el valle es una experiencia onírica. Un cielo lleno de globos de colores sobre formaciones rocosas únicas en el mundo crea una postal viviente.",
        parrafo3: "Desde el aire, entiendes la magnitud de Cappadocia y cómo la gente excavó sus casas en la roca blanda. El piloto manejaba el globo con una precisión increíble, acercándonos a las formaciones.",
        parrafo4: "Al aterrizar, brindamos con champán, una tradición encantadora. Turquía nos robó el corazón, pero este amanecer se lleva la palma.",
        likes: 45
    },
    {
        id: "EXP010",
        titulo: "Filipinas, cuevas y laguna de El Nido",
        subtitulo: "El paraíso acuático definitivo",
        autor: "Marc T.",
        fecha_publicacion: "14/02/2024",
        pack_asociado: "ASIA007PH",
        imagen1: "../images/ex-filipinas.jpg",
        imagen2: "../images/ex-filipinas.jpg",
        parrafo1: "El Nido hace honor a su fama. Navegar en kayak entre aguas turquesas y formaciones kársticas gigantes es sentirse en la película 'La Playa'. El agua es tan clara que ves el fondo a metros de profundidad.",
        parrafo2: "Entrar en el Big Lagoon con el kayak fue el momento cumbre. Las paredes de roca negra contrastan con el azul eléctrico del agua. Es un lugar que transmite una paz inmensa, a pesar de ser turístico.",
        parrafo3: "Exploramos cuevas escondidas a las que solo se accede buceando o agachándose mucho. Dentro, catedrales de roca natural nos esperaban. La sensación de descubrimiento es constante.",
        parrafo4: "Filipinas es agua, sonrisas y atardeceres de fuego. Si te gusta el mar, no hay lugar mejor en el mundo para perderse.",
        likes: 29
    },
    {
        id: "EXP011",
        titulo: "Un safari en Masai Mara, Kenia",
        subtitulo: "El ciclo de la vida en directo",
        autor: "Familia Ruiz",
        fecha_publicacion: "20/07/2024",
        pack_asociado: "AFR004KE",
        imagen1: "../images/ex-kenia.jpg",
        imagen2: "../images/ex-kenia.jpg",
        parrafo1: "Llevar a nuestros hijos a Kenia fue la mejor decisión. Ver a los animales en libertad, en su casa, es la mejor educación posible. Los cinco grandes imponen, pero ver a las manadas de ñus moverse es hipnótico.",
        parrafo2: "Tuvimos la suerte de ver una cacería de guepardos. Es duro, pero es la naturaleza en estado puro. Nuestros guías fueron respetuosos y expertos, enseñándonos a leer las huellas y señales.",
        parrafo3: "Las puestas de sol en la sabana son épicas. El cielo se tiñe de rojo sangre y las siluetas de las acacias se recortan en el horizonte. Es la imagen icónica de África que todos tenemos en la mente.",
        parrafo4: "Dormir en tiendas de campaña escuchando los sonidos de la noche africana añade un punto de aventura que nos unió mucho como familia.",
        likes: 52
    },
    {
        id: "EXP012",
        titulo: "Ver las luces de Shibuya de noche",
        subtitulo: "Perdidos en la traducción",
        autor: "Irene V.",
        fecha_publicacion: "11/11/2024",
        pack_asociado: "ASIA001JP",
        imagen1: "../images/ex-shibuya.jpg",
        imagen2: "../images/ex-shibuya.jpg",
        parrafo1: "Había visto el cruce de Shibuya mil veces en películas, pero estar allí es otra cosa. Cuando el semáforo se pone verde, una marea humana invade el asfalto. Es el caos más ordenado del mundo.",
        parrafo2: "Subimos a uno de los edificios cercanos para verlo desde arriba. Las pantallas gigantes, los neones, la gente... es una sobrecarga sensorial maravillosa. Te sientes como en una película de ciencia ficción.",
        parrafo3: "Explorar las callejuelas alrededor de Shibuya nos llevó a descubrir bares diminutos y tiendas de música increíbles. Tokyo nunca duerme y Shibuya es su corazón palpitante.",
        parrafo4: "Es el contraste perfecto con la tranquilidad de los templos. Japón es eso: silencio zen y ruido de neón. Y me encantan las dos caras.",
        likes: 41
    }
];

window.EXPERIENCIAS = EXPERIENCIAS;