const EXPERIENCIAS = [
    // --- EXPERIENCIAS ORIGINALES ---
    {
        id: "EXP001",
        titulo: "El silencio de los bambúes",
        subtitulo: "Cómo encontré la paz en medio del caos de Arashiyama",
        autor: "Laura G.",
        fecha_publicacion: "12/03/2024",
        pack_asociado: "ASIA001JP", 
        imagen1: "../images/ex-bambu.jpg",
        imagen2: "../images/ex-bambu1.jpg",
        parrafo1: "Siempre pensé que Japón sería ruido, neones y gente corriendo por todas partes. Y lo es, especialmente en Tokyo. Pero cuando llegué a Kyoto, algo cambió dentro de mí. El ritmo de la ciudad antigua es diferente, como si el tiempo hubiera decidido tomarse un descanso entre templo y templo.",
        parrafo2: "El momento más mágico fue al amanecer en el bosque de bambú de Arashiyama. Nos levantamos a las 5:00 AM para evitar las multitudes. El frío de la mañana se colaba por la ropa, pero valió la pena. Estar allí sola, escuchando solo el crujir de los troncos chocando con el viento, fue una experiencia casi religiosa.",
        parrafo3: "Después del paseo, nos refugiamos en una pequeña casa de té cercana. Allí probé por primera vez el matcha auténtico, batido con mimo por una anciana que no hablaba ni una palabra de inglés, pero cuya sonrisa entendía perfectamente mi gratitud. Fue un contraste brutal con la noche anterior de karaoke y luces en Osaka.",
        parrafo4: "Recomiendo este viaje a cualquiera que sienta que su vida va demasiado rápido. Japón te enseña que la modernidad más absoluta puede convivir con la tradición más pausada. Volveré, sin duda, para ver los cerezos en flor.",
        likes: 34
    },
    {
        id: "EXP002",
        titulo: "Despertar entre leones",
        subtitulo: "Mi primera vez en un safari y por qué lloré al ver un elefante",
        autor: "Carlos M.",
        fecha_publicacion: "05/02/2024",
        pack_asociado: "AFR004KE", 
        imagen1: "../images/ex-elefante.jpg",
        imagen2: "../images/ex-elefante1.jpg",
        parrafo1: "Nada te prepara para la inmensidad de África. Había visto documentales toda mi vida, pero el olor de la tierra mojada y el sonido de la sabana no se pueden transmitir por televisión. Al llegar al Masai Mara, sentí que estaba entrando en el verdadero reino animal, donde nosotros somos solo invitados.",
        parrafo2: "La primera mañana salimos antes de que saliera el sol. Nuestro guía, Joseph, detuvo el jeep de repente y señaló un arbusto. Al principio no vi nada, pero luego, una melena dorada se movió. Un león macho estaba a escasos cinco metros de nosotros, bostezando indiferente a nuestra presencia.",
        parrafo3: "Pero lo que realmente me rompió fue el encuentro con una familia de elefantes. Ver cómo las madres protegían a la cría más pequeña, con esa ternura y fuerza a la vez, me hizo llorar de emoción. Es una lección de humildad brutal darte cuenta de lo pequeños que somos al lado de estos gigantes.",
        parrafo4: "Las noches en el campamento eran otro mundo. Cenar bajo un cielo con más estrellas de las que creía que existían, escuchando hienas a lo lejos, es algo que te cambia la perspectiva. Si tienes dudas sobre si ir a África: ve. Es el viaje de tu vida.",
        likes: 58
    },
    {
        id: "EXP003",
        titulo: "Caminando hacia las nubes",
        subtitulo: "El reto físico y mental de llegar a Machu Picchu",
        autor: "Ana y David",
        fecha_publicacion: "20/01/2024",
        pack_asociado: "LATAM006PE", 
        imagen1: "../images/ex-nubes_MP.jpg",
        imagen2: "../images/ex-nubes_MP1.jpg",
        parrafo1: "Llegar a Cusco ya es una aventura en sí misma. La altura se nota nada más bajar del avión, pero la energía de la ciudad te empuja a seguir. Pasamos dos días aclimatándonos, bebiendo mate de coca y perdiéndonos por las calles de piedra que cuentan historias de dos imperios.",
        parrafo2: "El camino hacia Aguas Calientes fue espectacular, viendo cómo el paisaje cambiaba de montañas áridas a selva húmeda. Pero nada se compara al momento en que entras en la ciudadela. Eran las 6 de la mañana y la niebla cubría todo. Poco a poco, el sol empezó a disipar las nubes y Huayna Picchu apareció frente a nosotros.",
        parrafo3: "No es solo ver las ruinas, es entender cómo vivían allí, cómo construyeron algo tan perfecto en un lugar tan inaccesible. Nuestro guía nos explicó la conexión astronómica de cada piedra, y te das cuenta de que los Incas no solo eran constructores, eran ingenieros del universo.",
        parrafo4: "Terminamos el viaje en Lima, disfrutando de la que dicen es la mejor gastronomía del mundo (y confirmamos que el ceviche allí es de otro planeta). Perú es intenso, agotador a veces, pero infinitamente gratificante.",
        likes: 47
    },

    

    {
        id: "EXP004",
        titulo: "Experiencia Colombia",
        subtitulo: "Café, salsa y la calidez de su gente",
        autor: "Marta R.",
        fecha_publicacion: "15/04/2024",
        pack_asociado: "LATAM001CO",
        imagen1: "../images/ex-colombia.jpg",
        imagen2: "../images/ex-colombia1.jpg", 
        imagen3: "../images/ex-colombia2.jpg",
        parrafo1: "Colombia te atrapa desde el primer 'Buenos días'. Recorrer los paisajes tropicales del Eje Cafetero fue como entrar en una postal verde infinita. El aroma a café recién tostado por las mañanas se convirtió en mi despertador favorito.",
        parrafo2: "En Medellín descubrí una ciudad que ha sabido reinventarse a través del arte y la cultura. Caminar por la Comuna 13 y ver los grafitis llenos de historia fue una lección de resiliencia que me llevo para siempre.",
        parrafo3: "Pero lo mejor, sin duda, es la alegría única del pueblo colombiano. Da igual dónde vayas, siempre hay música, una sonrisa y alguien dispuesto a ayudarte. Bailar salsa (o intentarlo) en Cali fue el broche de oro.",
        parrafo4: "Es un país que rompe con todos los estereotipos. Me sentí segura, bienvenida y parte de una gran familia. Si buscas un destino con alma, Colombia es el lugar.",
        likes: 39
    },
    {
        id: "EXP005",
        titulo: "Vietnam y sus sendas escondidas",
        subtitulo: "Entre arrozales y dragones de piedra",
        autor: "Javier S.",
        fecha_publicacion: "22/05/2024",
        pack_asociado: "ASIA006VN",
        imagen1: "../images/ex-vietnam.jpg",
        imagen2: "../images/ex-vietnam1.jpg",
        imagen3: "../images/ex-vietnam2.jpg",
        parrafo1: "Vietnam es un país que se vive con los cinco sentidos. El caos de las motos en Hanoi contrasta con la paz absoluta de navegar por la Bahía de Ha Long, donde las formaciones de roca parecen dragones durmiendo en el mar.",
        parrafo2: "Nos adentramos en templos ancestrales ocultos en cuevas, donde el olor a incienso crea una atmósfera mística. Visitar aldeas flotantes y ver cómo la vida transcurre sobre el agua fue una experiencia antropológica fascinante.",
        parrafo3: "Caminar por senderos rodeados de naturaleza salvaje en Sapa, entre terrazas de arroz de un verde imposible, me hizo conectar con la tierra de una forma nueva. Las etnias locales, con sus trajes coloridos, nos recibieron con curiosidad y amabilidad.",
        parrafo4: "Y la comida... ¡qué decir de la comida! Un simple Pho en un puesto callejero sabe a gloria. Vietnam es un viaje de descubrimiento constante, humilde y espectacular a la vez.",
        likes: 22
    },
    {
        id: "EXP006",
        titulo: "La ruta de los manglares por Panamá",
        subtitulo: "Naturaleza virgen entre dos océanos",
        autor: "Elena y Pablo",
        fecha_publicacion: "10/06/2024",
        pack_asociado: "LATAM007PA",
        imagen1: "../images/ex-panama.jpg",
        imagen2: "../images/ex-panama1.jpg",
        imagen3: "../images/ex-panama2.jpg",
        parrafo1: "Panamá es mucho más que su famoso canal. Navegar entre manglares fue como entrar en un laberinto de vida. El silencio solo se rompía por el canto de aves exóticas y el chapoteo de los remos.",
        parrafo2: "Descubrimos fauna que nunca habíamos visto en libertad: perezosos colgados de las ramas, monos aulladores y estrellas de mar gigantes en el fondo cristalino. Es uno de los ecosistemas más fascinantes y frágiles que he visitado.",
        parrafo3: "La visita a las islas de Guna Yala nos permitió desconectar del mundo digital y reconectar con lo básico: sol, mar y arena blanca. Dormir en cabañas sencillas frente al Caribe es el verdadero lujo.",
        parrafo4: "Panamá nos sorprendió por su biodiversidad y por lo fácil que es pasar de la selva más densa a una ciudad de rascacielos en pocas horas. Un destino completo y sorprendente.",
        likes: 27
    },
    {
        id: "EXP007",
        titulo: "Exploración de glaciares en Islandia",
        subtitulo: "Caminando sobre el hielo azul eterno",
        autor: "Roberto K.",
        fecha_publicacion: "05/01/2024",
        pack_asociado: "EUR002IS",
        imagen1: "../images/ex-islandia.jpg",
        imagen2: "../images/ex-islandia1.jpg",
        parrafo1: "Islandia parece otro planeta. Ponerse los crampones y caminar sobre antiguas masas de hielo fue una de las cosas más emocionantes que he hecho. El crujido del glaciar bajo tus pies te recuerda que es una entidad viva.",
        parrafo2: "Descubrir cuevas de hielo fue mágico. Los tonos azules son imposibles de describir, parece que estás dentro de un zafiro gigante. La luz se filtra a través del hielo creando efectos visuales que ninguna cámara puede captar del todo.",
        parrafo3: "Más allá del hielo, las cascadas y los campos de lava te dejan sin aliento. Es una tierra de contrastes brutales, donde el fuego y el hielo han moldeado un paisaje dramático y hermoso.",
        parrafo4: "Aunque el frío aprieta, la calidez de los baños termales al final del día lo cura todo. Ver auroras boreales bailando sobre el glaciar fue el regalo final de este viaje épico.",
        likes:60
    },
    {
        id: "EXP008",
        titulo: "Ruta a la Montaña de 7 colores en Perú",
        subtitulo: "Un arcoíris pintado en la tierra",
        autor: "Sofía L.",
        fecha_publicacion: "18/08/2024",
        pack_asociado: "LATAM006PE",
        imagen1: "../images/ex-peru.jpg",
        imagen2: "../images/ex-peru1.jpg",
        parrafo1: "El trekking a Vinicunca no es fácil debido a la altitud, pero cada paso merece la pena. El paisaje andino te envuelve, con llamas y alpacas pastando libremente mientras subes hacia la cima.",
        parrafo2: "Cuando por fin llegas al mirador y ves la montaña frente a ti, te quedas sin palabras. Es un trekking único entre paisajes surrealistas, donde los minerales han pintado franjas de turquesa, lavanda y dorado en la ladera.",
        parrafo3: "El viento soplaba fuerte, pero la emoción nos mantenía calientes. Es increíble pensar en los procesos geológicos necesarios para crear algo así. Nos sentimos muy pequeños ante tanta majestuosidad.",
        parrafo4: "Recomiendo ir bien aclimatado y tomarse el ascenso con calma. Llegar arriba es una victoria personal y la vista es la mejor medalla que te puedes llevar.",
        likes: 18
    },
    {
        id: "EXP009",
        titulo: "Cappadocia en globo en Turquía",
        subtitulo: "Amanecer sobre un cuento de hadas",
        autor: "Daniel y Clara",
        fecha_publicacion: "30/09/2024",
        pack_asociado: "", // No tenemos pack de Turquía aún, dejamos vacío o creamos uno futuro
        imagen1: "../images/ex-turquia.jpg",
        imagen2: "../images/ex-turquia1.jpg",
        parrafo1: "Levantarse a las 4 de la mañana nunca había tenido tanto sentido. Ver cómo inflan los enormes globos en la oscuridad es el preludio de algo inolvidable. Cuando la cesta se despega del suelo, todo es silencio.",
        parrafo2: "Flotar sobre las 'chimeneas de hadas' mientras el sol empieza a iluminar el valle es una experiencia onírica. Un cielo lleno de globos de colores sobre formaciones rocosas únicas en el mundo crea una postal viviente.",
        parrafo3: "Desde el aire, entiendes la magnitud de Cappadocia y cómo la gente excavó sus casas en la roca blanda. El piloto manejaba el globo con una precisión increíble, acercándonos a las formaciones.",
        parrafo4: "Al aterrizar, brindamos con champán, una tradición encantadora. Turquía nos robó el corazón, pero este amanecer se lleva la palma.",
        likes: 45
    },
    {
        id: "EXP010",
        titulo: "Filipinas, cuevas y laguna de El Nido",
        subtitulo: "El paraíso acuático definitivo",
        autor: "Marc T.",
        fecha_publicacion: "14/02/2024",
        pack_asociado: "ASIA007PH",
        imagen1: "../images/ex-filipinas.jpg",
        imagen2: "../images/ex-filipinas1.jpg",
        parrafo1: "El Nido hace honor a su fama. Navegar en kayak entre aguas turquesas y formaciones kársticas gigantes es sentirse en la película 'La Playa'. El agua es tan clara que ves el fondo a metros de profundidad.",
        parrafo2: "Entrar en el Big Lagoon con el kayak fue el momento cumbre. Las paredes de roca negra contrastan con el azul eléctrico del agua. Es un lugar que transmite una paz inmensa, a pesar de ser turístico.",
        parrafo3: "Exploramos cuevas escondidas a las que solo se accede buceando o agachándose mucho. Dentro, catedrales de roca natural nos esperaban. La sensación de descubrimiento es constante.",
        parrafo4: "Filipinas es agua, sonrisas y atardeceres de fuego. Si te gusta el mar, no hay lugar mejor en el mundo para perderse.",
        likes: 29
    },
    {
        id: "EXP011",
        titulo: "Un safari en Masai Mara, Kenia",
        subtitulo: "El ciclo de la vida en directo",
        autor: "Familia Ruiz",
        fecha_publicacion: "20/07/2024",
        pack_asociado: "AFR004KE",
        imagen1: "../images/ex-kenia.jpg",
        imagen2: "../images/ex-kenia1.jpg",
        parrafo1: "Llevar a nuestros hijos a Kenia fue la mejor decisión. Ver a los animales en libertad, en su casa, es la mejor educación posible. Los cinco grandes imponen, pero ver a las manadas de ñus moverse es hipnótico.",
        parrafo2: "Tuvimos la suerte de ver una cacería de guepardos. Es duro, pero es la naturaleza en estado puro. Nuestros guías fueron respetuosos y expertos, enseñándonos a leer las huellas y señales.",
        parrafo3: "Las puestas de sol en la sabana son épicas. El cielo se tiñe de rojo sangre y las siluetas de las acacias se recortan en el horizonte. Es la imagen icónica de África que todos tenemos en la mente.",
        parrafo4: "Dormir en tiendas de campaña escuchando los sonidos de la noche africana añade un punto de aventura que nos unió mucho como familia.",
        likes: 52
    },
    {
        id: "EXP012",
        titulo: "Ver las luces de Shibuya de noche",
        subtitulo: "Perdidos en la traducción",
        autor: "Irene V.",
        fecha_publicacion: "11/11/2024",
        pack_asociado: "ASIA001JP",
        imagen1: "../images/ex-shibuya.jpg",
        imagen2: "../images/ex-shibuya1.jpg",
        parrafo1: "Había visto el cruce de Shibuya mil veces en películas, pero estar allí es otra cosa. Cuando el semáforo se pone verde, una marea humana invade el asfalto. Es el caos más ordenado del mundo.",
        parrafo2: "Subimos a uno de los edificios cercanos para verlo desde arriba. Las pantallas gigantes, los neones, la gente... es una sobrecarga sensorial maravillosa. Te sientes como en una película de ciencia ficción.",
        parrafo3: "Explorar las callejuelas alrededor de Shibuya nos llevó a descubrir bares diminutos y tiendas de música increíbles. Tokyo nunca duerme y Shibuya es su corazón palpitante.",
        parrafo4: "Es el contraste perfecto con la tranquilidad de los templos. Japón es eso: silencio zen y ruido de neón. Y me encantan las dos caras.",
        likes: 41
    },

    {
        id: "EXP013",
        titulo: "Samba, Tango y contrastes",
        subtitulo: "Dos ciudades, dos ritmos, un viaje inolvidable",
        autor: "Valentina y Jorge",
        fecha_publicacion: "02/03/2024",
        pack_asociado: "LATAM003BR", 
        imagen1: "../images/ex-tango.jpg",
        imagen2: "../images/ex-tango2.jpg",
        imagen3: "../images/ex-tango3.jpg",
        parrafo1: "Empezar el viaje en Río de Janeiro es recibir una inyección de vida directa en las venas. La energía de Copacabana no se puede explicar, hay que vivirla. Subir al Pan de Azúcar y ver la ciudad encajada entre la selva y el mar te deja sin aliento.",
        parrafo2: "El cambio al llegar a Buenos Aires fue fascinante. Pasamos del calor tropical y la caipirinha a la elegancia europea y el vino Malbec. El barrio de San Telmo, con sus calles empedradas y bailarines de tango en las esquinas, tiene una melancolía preciosa.",
        parrafo3: "Lo que más disfrutamos fue la comida. En Brasil, la feijoada nos dio energía para bailar samba (o intentarlo), mientras que el asado en Argentina superó todas nuestras expectativas. Son dos culturas muy distintas que se complementan a la perfección.",
        parrafo4: "Es el viaje ideal si quieres ver las dos caras de la moneda sudamericana en poco tiempo. Volvemos con la maleta llena de alfajores y el corazón lleno de música.",
        likes: 64
    },
    {
        id: "EXP014",
        titulo: "El caos delicioso de Bangkok",
        subtitulo: "Perdiéndome entre templos dorados y comida callejera",
        autor: "Lucas D.",
        fecha_publicacion: "12/05/2024",
        pack_asociado: "ASIA005TH",
        imagen1: "../images/ex-bangkok.jpg",
        imagen2: "../images/ex-bangkok1.jpg",
        parrafo1: "Bangkok te golpea nada más salir del aeropuerto: el calor, la humedad y el ruido. Pero una vez te dejas llevar, descubres su magia. Moverse en Skytrain es fácil, pero la verdadera aventura fue mi primer viaje en Tuk-tuk negociando el precio con señas.",
        parrafo2: "La visita a Ayutthaya fue el contrapunto necesario. Caminar entre las ruinas de ladrillo rojo y ver las cabezas de Buda atrapadas en las raíces de los árboles te transporta a otra época. Es impresionante imaginar la grandeza que tuvo este reino.",
        parrafo3: "Soy un amante de la comida y este viaje fue mi paraíso. Comí el mejor Pad Thai de mi vida en un taburete de plástico en la calle por menos de dos euros. Los sabores son intensos: picante, dulce, ácido y salado, todo a la vez.",
        parrafo4: "Si vas, no te pierdas el atardecer frente al Wat Arun desde el otro lado del río. Ver cómo se ilumina el templo mientras el cielo se oscurece es una imagen que se te queda grabada para siempre.",
        likes: 48
    },
    {
        id: "EXP015",
        titulo: "Guardianes de la arena",
        subtitulo: "Un viaje al pasado frente a las grandes pirámides",
        autor: "Sara P.",
        fecha_publicacion: "28/09/2024",
        pack_asociado: "AFR005EG",
        imagen1: "../images/ex-egipto.jpg",
        imagen2: "../images/ex-egipto1.jpg",
        parrafo1: "Había estudiado el Antiguo Egipto en el colegio, pero tener la Gran Pirámide de Giza frente a ti es una experiencia que te hace sentir minúsculo. La precisión de los bloques y la inmensidad de la estructura desafían toda lógica.",
        parrafo2: "El Cairo es una ciudad frenética, ruidosa y polvorienta, pero llena de vida. El Museo Egipcio es un laberinto de tesoros; ver la máscara de Tutankamón en persona me puso la piel de gallina. Se respira historia en cada vitrina.",
        parrafo3: "El momento de paz llegó con el paseo en feluca por el Nilo al atardecer. El contraste entre el bullicio de la ciudad y la calma del río es brutal. El viento en las velas y el sol rojo cayendo sobre el agua fue mi momento favorito.",
        parrafo4: "Egipto es intenso y a veces agobiante por el calor y los vendedores, pero es un destino obligatorio para entender la historia de la humanidad. Me voy con ganas de bajar hasta Luxor la próxima vez.",
        likes: 72
    },
    {
        id: "EXP016",
        titulo: "Invierno bajo la Aurora Boreal",
        subtitulo: "Una ruta en 4x4 por la Islandia más salvaje",
        autor: "Grupo 'Los Vikingos'",
        fecha_publicacion: "15/01/2024",
        pack_asociado: "EUR002IS",
        imagen1: "../images/ex-islandia-noche.jpg",
        imagen2: "../images/ex-islandia-noche1.jpg",
        parrafo1: "Decidimos ir en invierno y fue un acierto total. Conducir el 4x4 por carreteras nevadas fue una aventura en sí misma. El paisaje blanco infinito, roto solo por rocas negras volcánicas, parece sacado de 'Juego de Tronos'.",
        parrafo2: "La cueva de hielo fue lo más surrealista que hemos visto. Entrar en las entrañas del glaciar y ver ese azul eléctrico sobre nuestras cabezas no parece de este mundo. El guía nos explicó cómo cambian cada año, lo que lo hace aún más especial.",
        parrafo3: "Tuvimos suerte. La tercera noche, cerca de Vík, el cielo se iluminó. Ver las auroras boreales bailar en verde y violeta sobre la iglesia negra fue el momento cumbre del viaje. Nos quedamos horas mirando al cielo a pesar del frío.",
        parrafo4: "Islandia es cara, no lo vamos a negar, pero la naturaleza allí es tan pura y brutal que cada euro vale la pena. Bañarse en aguas termales mientras nieva fuera es el broche de oro.",
        likes: 89
    },

    {
        id: "EXP017",
        titulo: "Aventura en Costa Rica",
        subtitulo: "Selva, volcanes y playas paradisíacas",
        autor: "Mónica F.",
        fecha_publicacion: "08/06/2024",
        pack_asociado: "LATAM005CR",
        imagen1: "../images/ex-costarica.jpg",
        imagen2: "../images/ex-costarica1.jpg",
        imagen3: "../images/ex-costarica2.jpg",
        parrafo1: "Costa Rica es un destino que lo tiene todo. Desde el momento en que llegas, la biodiversidad te envuelve. Me daba un poco de miedo venir con niños, pero es un destino muy family friendly. Hicimos canopy en Monteverde y sentirnos suspendidos entre las copas de los árboles fue una experiencia única.",
        parrafo2: "El volcán Arenal nos dejó sin aliento, no solo por su imponente presencia, sino por las aguas termales naturales que lo rodean. Relajarse en esas piscinas calientes mientras ves el volcán humeante es algo que no olvidaré jamás.",
        parrafo3: "Las playas de Manuel Antonio son un paraíso. La combinación de selva y mar crea un ecosistema increíble. Ver monos y perezosos mientras tomas el sol es algo que solo Costa Rica puede ofrecer.",
        parrafo4: "La gente es increíblemente amable, lo que hace que el viaje sea aún más especial. Volveré seguro para seguir explorando sus rincones.",
        likes: 37
    },

    {
        id: "EXP018",
        titulo: "Escalada en Nepal",
        subtitulo: "Entre montañas sagradas y aldeas remotas",
        autor: "Fernando G.",
        fecha_publicacion: "25/04/2024",
        pack_asociado: "ASIA004NP",
        imagen1: "../images/ex-nepal.jpg",
        imagen2: "../images/ex-nepal1.jpg",
        parrafo1: "Nepal es un destino que desafía tus límites. La caminata hacia el campamento base del Everest fue dura, pero cada paso valió la pena. Las vistas de las montañas sagradas te llenan de una energía indescriptible.",
        parrafo2: "Las aldeas que cruzamos nos mostraron una cultura rica y acogedora. Compartir momentos con los sherpas y aprender sobre sus tradiciones fue tan enriquecedor como la propia escalada.",
        parrafo3: "El momento más emotivo fue llegar al campamento base y ver el Everest de cerca. Es una montaña que impone respeto y admiración. Sentí una mezcla de humildad y logro personal que nunca olvidaré.",
        parrafo4: "Nepal me enseñó la importancia de la perseverancia y el respeto por la naturaleza. Es un destino para los aventureros de corazón.",
        likes: 55
    }

    


];

window.EXPERIENCIAS = EXPERIENCIAS;